### PR TITLE
Improve UI demo to fix issue #67.

### PR DESCRIPTION
**Pull request by risdenk**
- Removed view*
- Removed index*
- changed elasticuidemo.html to index.html
- removed couchbasedemofiles folder

### CODE REVIEW

**Comment by risdenk** [comment]
Related to #78

**Comment by risdenk** [comment]
TODO: Need to fix CSS issues w/ new version of bootstrap.

**Comment by risdenk** [comment]
Still one minor issue w/ the css. Checkbox for multi select filter is outside the panel. This looks like an incompatibility between the panel and the checkbox for elasticui.

**Comment by risdenk** [comment]
Filed #87 to address the minor CSS issue.

@kruthar can you review?

**Comment by kruthar** [comment]
Looks ok to me.

@cricket007 does it work?

**Comment by OneCricketeer** [comment]
:+1:

**Pull request merged**
